# SLURM arguments
# slurm_account: gliugroup_gpu     
slurm_partition: gpu
slurm_array_parallelism: 4 # Limit job concurrency to 4 jobs at a time
nodes: 1 # Each job in the job array gets one node
mem_gb: 4 # Each job gets 4GB of memory
timeout_min: 2880 # Limit the job running time to 2 days (48 * 60)
slurm_gpus_per_node: 1, # Each node should use 1 GPU
slurm_additional_parameters: 
    account: gliugroup_gpu

# partition arguments
n_partitions: 4